name: 镜像搬运工

on:
  workflow_dispatch: # 允许你手动点击按钮开始搬运
  push:
    branches: [ "main" ] # 当你修改这个文件时也会自动触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. 登录到你的阿里云私人仓库
      - name: 登录阿里云
        uses: docker/login-action@v2
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALIYUN_USER }}
          password: ${{ secrets.ALIYUN_PWD }}

      # 2. 开始搬运（这里以 mysql:8.0.30 为例）
      - name: 批量搬运-拉取并推送到国内
        run: |
          # 定义一个镜像列表  多个就追加 mysql:8.0.30 redis:7.2.4 nginx:1.25.3
          images=(mysql:8.0.30)
          # 从官方拉取
          for img in "${images[@]}"; do
            docker pull $img
            docker tag $img registry.cn-hangzhou.aliyuncs.com/abc-mirror/$img
            # 推送到阿里云
            docker push registry.cn-hangzhou.aliyuncs.com/abc-mirror/$img
          done
